solve stairs problem
MIT-Emerging-Talent/2024-group-11-collaboration-practice pull request #32
Opened 2024-01-20 11:34 UTC by YaninaChukanova

- [ ] PR's title includes the challenge's name and language
- [ ] PR has short and clear description of the challenge
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] all conflicts are resolved (if any)
- [ ] It is linked to an issue in the appropriate column of the project board
- [ ] feedback is addressed (if any, and if it is appropriate feedback.)

## README Documentation

- [ ] The solution is documented in `/src/README.md`
- [ ] The markdown source is formatted
- [ ] Spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] All links and images work
- [ ] The README documents the solution's behavior, strategy(ies) and implementation(s)
- [ ] There are use cases in code blocks to illustrate the function's behavior

## Python Files

- [ ] There is a module header
- [ ] There is a module docstring
- [ ] File names are in snake_case
- [ ] Test files are named `test_<module_name>.py`

## Function Docstring

- [ ] Behavior description
- [ ] Parameter description
- [ ] Return value description
- [ ] Include any assumptions
- [ ] Include 3 or more (passing!) doctests
- [ ] Include 1-2 use cases (if necessary)

## Function Implementation

- [ ] The solution is not is not copied from [djeada](https://github.com/djeada/Algorithms-And-Data-Structures)
- [ ] The code is auto-formatted
- [ ] The code has no (reasonable) linting mistakes
- [ ] Variables are named with snake_case
- [ ] The function has a clear and helpful name
- [ ] The file's name matches the function name
- [ ] The code follows the strategy as simply as possible
- [ ] Variable names are clear and helpful
- [ ] Comments explain the strategy (if necessary)
- [ ] There are type annotations
- [ ] (challenge) The code includes defensive assertions

## Unit Test Suite

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Each unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases
- [ ] Test suite includes black-box and glass-box tests

2024-01-21 11:22 UTC, AnnaShliapkina requested changes

2024-01-21 11:22 UTC, AnnaShliapkina commented on src/dynamic_programming/python/climbing_stairs/src/climb.py
>      )
All explanation you added in README you can (and should) put in docstrings before each function. This file also need documentation.

2024-01-21 11:22 UTC, AnnaShliapkina commented on src/dynamic_programming/python/climbing_stairs/src/climb.py
The solution is similar to djeada solution

2024-01-21 11:22 UTC, AnnaShliapkina commented on src/dynamic_programming/python/climbing_stairs/tests/test_climbing_stairs.py
![image](https://github.com/MIT-Emerging-Talent/2024-group-11-collaboration-practice/assets/96006835/8668273c-248b-4901-8a57-ea1d4cec97ee)

One test are not pass

2024-01-21 19:37 UTC, DmytroLyt submitted a review, later dismissed
- PR's title includes the challenge's name and language **(i didn`t find this challenge, maybe problems with naming of pull request? Also need add language)**
(Remember use PEP8 standard, code 
- There is a module header (Doesn`t have, Need to add )
- There is a module docstring (Doesn`t have, Need to add )

File climb.py need attention:
-  Behavior description (Doesn`t have, Need to add )
-  Parameter description (Doesn`t have, Need to add )
-  Return value description (Doesn`t have, Need to add )
-  The solution is not is not copied from [djeada] ( Code is looks like copied from that repo, need another solution) 


-  The test class has a docstring (Doesn`t have, Need to add )
- All tests pass ( One test failed)

2024-01-22 19:50 UTC, AnnaShliapkina approved these changes

2024-01-22 19:50 UTC, merged