Solve quick_sort probem
MIT-Emerging-Talent/2024-group-11-collaboration-practice pull request #34
Opened 2024-01-20 19:21 UTC by YaninaChukanova

- [ ] PR's title includes the challenge's name and language
- [ ] PR has short and clear description of the challenge
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] all conflicts are resolved (if any)
- [ ] It is linked to an issue in the appropriate column of the project board
- [ ] feedback is addressed (if any, and if it is appropriate feedback.)

## README Documentation

- [ ] The solution is documented in `/src/README.md`
- [ ] The markdown source is formatted
- [ ] Spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] All links and images work
- [ ] The README documents the solution's behavior, strategy(ies) and implementation(s)
- [ ] There are use cases in code blocks to illustrate the function's behavior

## Python Files

- [ ] There is a module header
- [ ] There is a module docstring
- [ ] File names are in snake_case
- [ ] Test files are named `test_<module_name>.py`

## Function Docstring

- [ ] Behavior description
- [ ] Parameter description
- [ ] Return value description
- [ ] Include any assumptions
- [ ] Include 3 or more (passing!) doctests
- [ ] Include 1-2 use cases (if necessary)

## Function Implementation

- [ ] The solution is not is not copied from [djeada](https://github.com/djeada/Algorithms-And-Data-Structures)
- [ ] The code is auto-formatted
- [ ] The code has no (reasonable) linting mistakes
- [ ] Variables are named with snake_case
- [ ] The function has a clear and helpful name
- [ ] The file's name matches the function name
- [ ] The code follows the strategy as simply as possible
- [ ] Variable names are clear and helpful
- [ ] Comments explain the strategy (if necessary)
- [ ] There are type annotations
- [ ] (challenge) The code includes defensive assertions

## Unit Test Suite

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Each unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases
- [ ] Test suite includes black-box and glass-box tests

2024-01-21 19:01 UTC, AnnaShliapkina requested changes

2024-01-21 19:01 UTC, AnnaShliapkina commented on src/sorting/python/quick_sort/README.md
All explanation you added in README you can (and should) put in docstrings before each function. This file also need documentation.

README filled in a little bit different way it should be. Check requirements for README.md

2024-01-21 19:01 UTC, AnnaShliapkina commented on src/sorting/python/quick_sort/src/quick_sort.py
Add behavior, explanation of attributes and returns.

2024-01-21 19:51 UTC, DmytroLyt requested changes
-  PR's title includes the challenge's name and language (language doesn`t exist)
- PR it is assigned to the owner ( PR is not assigned at all, Need to assign)
- The README documents the solution's behavior, strategy(ies) and implementation(s) ( Need to be structured and not clean explanation)
- There is a module header (Doesn`t have, Need to add)
-  There is a module docstring (Doesn`t have, Need to add)
- The solution is not is not copied from [djeada](https://github.com/djeada/Algorithms-And-Data-Structures) _( Code is copied, just was changed variables names, need another solution)_
- The test class has a docstring  (Doesn`t have, Need to add)

2024-01-22 23:34 UTC, DmytroLyt approved these changes
Issues solved

2024-01-22 23:35 UTC, AnnaShliapkina commented on src/sorting/python/quick_sort/README.md
Checked. Everything solved

2024-01-22 23:35 UTC, AnnaShliapkina approved these changes

2024-01-22 23:43 UTC, merged